/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalreservationsystem;

/**
 *
 * @author Lenovo
 */
public class adminpage extends javax.swing.JFrame {

    /**
     * Creates new form adminpage
     */
    public adminpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editpasswordbutton = new javax.swing.JButton();
        adddoctorbutton = new javax.swing.JButton();
        deletedoctorbutton = new javax.swing.JButton();
        viewdoctorbutton = new javax.swing.JButton();
        returntohomepagebutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204 ,80));

        editpasswordbutton.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        editpasswordbutton.setText("edit your password");
        editpasswordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpasswordbuttonActionPerformed(evt);
            }
        });

        adddoctorbutton.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        adddoctorbutton.setText("add a doctor to the system");
        adddoctorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddoctorbuttonActionPerformed(evt);
            }
        });

        deletedoctorbutton.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        deletedoctorbutton.setText("delete a doctor from a system");
        deletedoctorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedoctorbuttonActionPerformed(evt);
            }
        });

        viewdoctorbutton.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        viewdoctorbutton.setText("view the doctors on system");
        viewdoctorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdoctorbuttonActionPerformed(evt);
            }
        });

        returntohomepagebutton.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        returntohomepagebutton.setText("return to home page");
        returntohomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returntohomepagebuttonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("admin page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editpasswordbutton)
                            .addComponent(deletedoctorbutton)
                            .addComponent(viewdoctorbutton)
                            .addComponent(returntohomepagebutton)
                            .addComponent(adddoctorbutton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel2)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(editpasswordbutton)
                .addGap(18, 18, 18)
                .addComponent(adddoctorbutton)
                .addGap(27, 27, 27)
                .addComponent(deletedoctorbutton)
                .addGap(18, 18, 18)
                .addComponent(viewdoctorbutton)
                .addGap(18, 18, 18)
                .addComponent(returntohomepagebutton)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 590, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalreservationsystem/2022-12-16 (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 590));

        setSize(new java.awt.Dimension(892, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returntohomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returntohomepagebuttonActionPerformed
        // TODO add your handling code here:
        homepage p= new homepage();
            p.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_returntohomepagebuttonActionPerformed

    private void editpasswordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpasswordbuttonActionPerformed
        // TODO add your handling code here:
        editadminpasswordpage p= new editadminpasswordpage();
            p.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_editpasswordbuttonActionPerformed

    private void adddoctorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddoctorbuttonActionPerformed
        // TODO add your handling code here:
        doctoraddingpage p= new doctoraddingpage();
            p.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_adddoctorbuttonActionPerformed

    private void deletedoctorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedoctorbuttonActionPerformed
        // TODO add your handling code here:
        doctordeletingpage p= new doctordeletingpage();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deletedoctorbuttonActionPerformed

    private void viewdoctorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdoctorbuttonActionPerformed
        // TODO add your handling code here:
        doctorsviewingpage p= new doctorsviewingpage();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewdoctorbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddoctorbutton;
    private javax.swing.JButton deletedoctorbutton;
    private javax.swing.JButton editpasswordbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton returntohomepagebutton;
    private javax.swing.JButton viewdoctorbutton;
    // End of variables declaration//GEN-END:variables
}
