/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalreservationsystem;
import java.sql.*;


/**
 *
 * @author Lenovo
 */
public class registerationpage extends javax.swing.JFrame {

    /**
     * Creates new form registerationpage
     */
    private static int flag1=0;
    private static int flag2=0;
   private static int flag3=0;
    private static int flag4=0;
    private static int flag5=0;
    private static int flag6=0;
   private static int flag7=0;
   private static int flag8=0;
    
    private static String ppn="";
    private static String pnid="";
    private static String pp="";
    private static String pn="";
    private static String paddress="";
    private static String pg="";
    private static String pu="";
    private static String pd="";
    private static String pm="";
    private static String py="";
     
//ppn:patientphonenumber  
//pnid:patient national id
//pp:patient password
//pn:patient name
//paddress: patient address
//pg:patient gender
//pu: patient user name
//pd: patientbirthday
//pm:patient birth month
//py:patient birth year
    
    public registerationpage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        phonenumberlabel = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        genderlabel = new javax.swing.JLabel();
        dateofbirthlabel = new javax.swing.JLabel();
        nationalidlabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        genderlist = new javax.swing.JComboBox<>();
        dayslist = new javax.swing.JComboBox<>();
        monthslist = new javax.swing.JComboBox<>();
        yearslist = new javax.swing.JComboBox<>();
        patientname = new javax.swing.JTextField();
        patientusername = new javax.swing.JTextField();
        patientphonenumber = new javax.swing.JTextField();
        patientnationalid = new javax.swing.JTextField();
        patientaddress = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        returntohomepagebutton = new javax.swing.JButton();
        patientpassword = new javax.swing.JPasswordField();
        checkname = new javax.swing.JLabel();
        checkaddress = new javax.swing.JLabel();
        checknationalid = new javax.swing.JLabel();
        checkphonenumber = new javax.swing.JLabel();
        checkdateofbirth = new javax.swing.JLabel();
        checkusername = new javax.swing.JLabel();
        checkpassword = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,150));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("registeration");

        namelabel.setBackground(new java.awt.Color(0, 0, 153));
        namelabel.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        namelabel.setText("name");

        passwordlabel.setBackground(new java.awt.Color(0, 0, 153));
        passwordlabel.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel.setText("password");

        phonenumberlabel.setBackground(new java.awt.Color(0, 0, 153));
        phonenumberlabel.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        phonenumberlabel.setForeground(new java.awt.Color(255, 255, 255));
        phonenumberlabel.setText("phone number");

        usernamelabel.setBackground(new java.awt.Color(0, 0, 153));
        usernamelabel.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        usernamelabel.setForeground(new java.awt.Color(255, 255, 255));
        usernamelabel.setText("username");

        genderlabel.setBackground(new java.awt.Color(0, 0, 153));
        genderlabel.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        genderlabel.setForeground(new java.awt.Color(255, 255, 255));
        genderlabel.setText("gender");

        dateofbirthlabel.setBackground(new java.awt.Color(0, 0, 153));
        dateofbirthlabel.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        dateofbirthlabel.setForeground(new java.awt.Color(255, 255, 255));
        dateofbirthlabel.setText("date of birth");

        nationalidlabel.setBackground(new java.awt.Color(0, 0, 153));
        nationalidlabel.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        nationalidlabel.setForeground(new java.awt.Color(255, 255, 255));
        nationalidlabel.setText("national ID");

        addresslabel.setBackground(new java.awt.Color(0, 0, 153));
        addresslabel.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        addresslabel.setForeground(new java.awt.Color(255, 255, 255));
        addresslabel.setText("address");

        genderlist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        genderlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        dayslist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dayslist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "day" }));

        monthslist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        monthslist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "january", "febraury", "march", "april", "may", "june", "july", "augist", "september", "october", "november", "december" }));
        monthslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthslistActionPerformed(evt);
            }
        });

        yearslist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearslist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));

        patientname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        patientusername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        patientphonenumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        patientnationalid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        patientaddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        submitbutton.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        submitbutton.setText("submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        resetbutton.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        resetbutton.setText("reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        returntohomepagebutton.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        returntohomepagebutton.setText("return to home page");
        returntohomepagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returntohomepagebuttonActionPerformed(evt);
            }
        });

        patientpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        checkname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkname.setForeground(new java.awt.Color(255, 0, 51));

        checkaddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkaddress.setForeground(new java.awt.Color(255, 0, 51));

        checknationalid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checknationalid.setForeground(new java.awt.Color(255, 0, 51));

        checkphonenumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkphonenumber.setForeground(new java.awt.Color(255, 0, 51));

        checkdateofbirth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkdateofbirth.setForeground(new java.awt.Color(255, 0, 51));

        checkusername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkusername.setForeground(new java.awt.Color(255, 0, 51));

        checkpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkpassword.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernamelabel)
                                        .addComponent(passwordlabel)
                                        .addComponent(phonenumberlabel)
                                        .addComponent(namelabel))
                                    .addGap(51, 51, 51)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(patientphonenumber)
                                        .addComponent(patientusername)
                                        .addComponent(patientname)
                                        .addComponent(patientpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                                .addComponent(checkpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(checkphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(99, 99, 99)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateofbirthlabel)
                                .addComponent(genderlabel)
                                .addComponent(nationalidlabel)
                                .addComponent(addresslabel))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(patientnationalid, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                        .addComponent(patientaddress)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(genderlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(yearslist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(monthslist, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dayslist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checknationalid, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkdateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(66, 66, 66))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(resetbutton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitbutton)
                    .addGap(151, 151, 151)
                    .addComponent(returntohomepagebutton)
                    .addGap(70, 70, 70)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(388, 388, 388))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(checkname, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel)
                    .addComponent(genderlabel)
                    .addComponent(genderlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateofbirthlabel)
                    .addComponent(usernamelabel)
                    .addComponent(monthslist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearslist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayslist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkdateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(checkusername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlabel)
                    .addComponent(nationalidlabel)
                    .addComponent(patientnationalid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checknationalid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonenumberlabel)
                    .addComponent(addresslabel)
                    .addComponent(patientphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitbutton)
                    .addComponent(resetbutton)
                    .addComponent(returntohomepagebutton))
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 1010, 570));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalreservationsystem/registerationpage image.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 740));

        setSize(new java.awt.Dimension(1285, 787));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void monthslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthslistActionPerformed
        // TODO add your handling code here:
       // System.out.println(monthslist.getComponentCount());
       // System.out.println(monthslist.getSelectedIndex());
        if(monthslist.getSelectedIndex()==1||monthslist.getSelectedIndex()==3||monthslist.getSelectedIndex()==5||monthslist.getSelectedIndex()==7||monthslist.getSelectedIndex()==8||monthslist.getSelectedIndex()==10||monthslist.getSelectedIndex()==12||monthslist.getSelectedIndex()==0){
            dayslist.removeAllItems();
            dayslist.addItem("day");
            dayslist.addItem("1");
            dayslist.addItem("2");
            dayslist.addItem("3");
            dayslist.addItem("4");
            dayslist.addItem("5");
            dayslist.addItem("6");
            dayslist.addItem("7");
            dayslist.addItem("8");
            dayslist.addItem("9");
            dayslist.addItem("10");
            dayslist.addItem("11");
            dayslist.addItem("12");
            dayslist.addItem("13");
            dayslist.addItem("14");
            dayslist.addItem("15");
            dayslist.addItem("16");
            dayslist.addItem("17");
            dayslist.addItem("18");
            dayslist.addItem("19");
            dayslist.addItem("20");
            dayslist.addItem("21");
            dayslist.addItem("22");
            dayslist.addItem("23");
            dayslist.addItem("24");
            dayslist.addItem("25");
            dayslist.addItem("26");
            dayslist.addItem("27");
            dayslist.addItem("28");
            dayslist.addItem("29");
            dayslist.addItem("30");
            dayslist.addItem("31");    
        }
        if(monthslist.getSelectedIndex()==2){
            dayslist.removeAllItems();
            dayslist.addItem("day");
            dayslist.addItem("1");
            dayslist.addItem("2");
            dayslist.addItem("3");
            dayslist.addItem("4");
            dayslist.addItem("5");
            dayslist.addItem("6");
            dayslist.addItem("7");
            dayslist.addItem("8");
            dayslist.addItem("9");
            dayslist.addItem("10");
            dayslist.addItem("11");
            dayslist.addItem("12");
            dayslist.addItem("13");
            dayslist.addItem("14");
            dayslist.addItem("15");
            dayslist.addItem("16");
            dayslist.addItem("17");
            dayslist.addItem("18");
            dayslist.addItem("19");
            dayslist.addItem("20");
            dayslist.addItem("21");
            dayslist.addItem("22");
            dayslist.addItem("23");
            dayslist.addItem("24");
            dayslist.addItem("25");
            dayslist.addItem("26");
            dayslist.addItem("27");
            dayslist.addItem("28");
            dayslist.addItem("29");
        } 
        if(monthslist.getSelectedIndex()==4||monthslist.getSelectedIndex()==6||monthslist.getSelectedIndex()==9||monthslist.getSelectedIndex()==11){
            dayslist.removeAllItems();
            dayslist.addItem("day");
            dayslist.addItem("1");
            dayslist.addItem("2");
            dayslist.addItem("3");
            dayslist.addItem("4");
            dayslist.addItem("5");
            dayslist.addItem("6");
            dayslist.addItem("7");
            dayslist.addItem("8");
            dayslist.addItem("9");
            dayslist.addItem("10");
            dayslist.addItem("11");
            dayslist.addItem("12");
            dayslist.addItem("13");
            dayslist.addItem("14");
            dayslist.addItem("15");
            dayslist.addItem("16");
            dayslist.addItem("17");
            dayslist.addItem("18");
            dayslist.addItem("19");
            dayslist.addItem("20");
            dayslist.addItem("21");
            dayslist.addItem("22");
            dayslist.addItem("23");
            dayslist.addItem("24");
            dayslist.addItem("25");
            dayslist.addItem("26");
            dayslist.addItem("27");
            dayslist.addItem("28");
            dayslist.addItem("29");
            dayslist.addItem("30");
        } 
     
    }//GEN-LAST:event_monthslistActionPerformed

    private void checkdata(){
        flag1=0;
        flag2=0;
        flag3=0;
        flag4=0;
        flag5=0;
        flag6=0;
        flag7=0;
        flag8=0; 
        checkphonenumber.setText("");
        checkdateofbirth.setText("");
         checknationalid.setText("");
         checkpassword.setText("");
         checkname.setText("");
         checkaddress.setText("");
         checkusername.setText("");
        ppn= patientphonenumber.getText();
        pnid= patientnationalid.getText();
        pg= genderlist.getSelectedItem().toString();
        pd= dayslist.getSelectedItem().toString();
        pm= monthslist.getSelectedItem().toString();
        py= yearslist.getSelectedItem().toString();
        pp= patientpassword.getText();
        pn=patientname.getText();
        paddress=patientaddress.getText();
        pu=patientusername.getText();
        if(ppn.equals("")){
            checkphonenumber.setText("please enter a valid phone number");
            flag1=1;
        }
        if(pd.equals("day")||pm.equals("month")||py.equals("year")){
            checkdateofbirth.setText("please enter your date of birth");
            flag3=1;
        }
        
        if(pnid.equals("")){
            checknationalid.setText("please enter a valid national id");
            flag2=1;
        }
        
        if(pp.equals("")){
            checkpassword.setText("please choose a password");
            flag4=1;
        }
        if(pn.equals("")){
            checkname.setText("please enter your name");
            flag5=1;
        }
        if(paddress.equals("")){
            checkaddress.setText("please enter your address");
            flag6=1;
        }
        
        if(pu.equals("")){
            checkusername.setText("please choose a username");
            flag7=1;
        }
        String url="jdbc:derby://localhost:1527/HOSPITALRESERVATIONSYSTEMDATABASE";
        String user="HAGER";
        String password="HAGER";
        String checku="";
         if(flag7==0){
        try{
            Connection con = DriverManager.getConnection(url, user, password);
            String s="SELECT PATIENTUSERNAME FROM HAGER.PATIENT" ;
           
           Statement st= con.createStatement();
           ResultSet rs= null;
           rs=st.executeQuery(s);
           while(rs.next()){
             checku=  rs.getString("PATIENTUSERNAME");
               if(checku.equals(pu)){
                   flag8=1;
               }
           }
           rs.close();
           st.close();
           con.close();
         
        }
        catch(SQLException e) {
            
            System.out.println("error");
        }
        }
         if(flag8==1){
             checkusername.setText("please choose another username");
         }
        
        
    }
    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        // TODO add your handling code here:
        patientname.setText("");
        patientaddress.setText("");
        patientusername.setText("");
        patientpassword.setText("");
        patientphonenumber.setText("");
        patientnationalid.setText("");
        genderlist.setSelectedIndex(0);
        dayslist.setSelectedIndex(0);
        monthslist.setSelectedIndex(0);
        yearslist.setSelectedIndex(0);
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void registeration(){
        checkdata();
       String url="jdbc:derby://localhost:1527/HOSPITALRESERVATIONSYSTEMDATABASE";
        String user="HAGER";
        String password="HAGER";
        if(flag1==0&&flag2==0&&flag3==0&&flag4==0&&flag5==0&&flag6==0&&flag7==0&&flag8==0){
        try{
            Connection con = DriverManager.getConnection(url, user, password);
            System.out.println("connected");
            String sql= "INSERT INTO HAGER.PATIENT(PATIENTPHONENUMBER,PATIENTNATIONAlID,PATIENTPASSWORD,PATIENTNAME,PATIENTADDRESS,PATIENTGENDER,PATIENTUSERNAME,PATIENTBIRTHDAY,PATIENTBIRTHMONTH,PATIENTBIRTHYEAR) VALUES('"+ppn+"','"+pnid+"','"+pp+"','"+pn+"','"+paddress+"','"+pg+"','"+pu+"','"+pd+"','"+pm+"','"+py+"')";
            Statement st=con.createStatement();
            st.executeUpdate(sql);
            st.close();
            con.close();

        }
        catch(SQLException e) {

            System.out.println("error");
        }
        loginpage p = new loginpage();
        p.setVisible(true);
         this.setVisible(false);}
    }
    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
       
        registeration();
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void returntohomepagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returntohomepagebuttonActionPerformed
        // TODO add your handling code here:
        homepage p = new homepage();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returntohomepagebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerationpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslabel;
    private javax.swing.JLabel checkaddress;
    private javax.swing.JLabel checkdateofbirth;
    private javax.swing.JLabel checkname;
    private javax.swing.JLabel checknationalid;
    private javax.swing.JLabel checkpassword;
    private javax.swing.JLabel checkphonenumber;
    private javax.swing.JLabel checkusername;
    private javax.swing.JLabel dateofbirthlabel;
    private javax.swing.JComboBox<String> dayslist;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JComboBox<String> genderlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> monthslist;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel nationalidlabel;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JTextField patientaddress;
    private javax.swing.JTextField patientname;
    private javax.swing.JTextField patientnationalid;
    private javax.swing.JPasswordField patientpassword;
    private javax.swing.JTextField patientphonenumber;
    private javax.swing.JTextField patientusername;
    private javax.swing.JLabel phonenumberlabel;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton returntohomepagebutton;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JComboBox<String> yearslist;
    // End of variables declaration//GEN-END:variables
}
